import json
import os
import random

os.makedirs("src/data", exist_ok=True)

# Comprehensive catalog definitions
categories = [
    # 1. FRESH VEGETABLES
    {
        "category": "Fresh Vegetables",
        "sub": "Daily Staples",
        "items": [
            ("Fresh Red Onion (Pyaz)", "Fresh Harvest", "Daily Staples", "1 kg", 55, 46, "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=500&auto=format&fit=crop&q=80", "Firm, flavorful red onions sourced fresh from regional mandis. Essential for Indian cooking.", ["onion", "pyaz", "kanda", "red onion", "vegetable"], True, True, False, "Best Price"),
            ("Fresh Farm Potatoes (Aloo)", "Fresh Harvest", "Daily Staples", "1 kg", 38, 30, "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500&auto=format&fit=crop&q=80", "Clean, uniform farm-fresh potatoes ideal for daily curries, fries, and roasts.", ["potato", "aloo", "batata", "potatoes"], True, True, True, "Great Value"),
            ("Fresh Hybrid Tomatoes", "Fresh Harvest", "Daily Staples", "1 kg", 42, 34, "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&auto=format&fit=crop&q=80", "Ripe red juicy hybrid tomatoes for curries, salads, and soups.", ["tomato", "tamatar", "tomatoes"], True, True, True, "Today's Deal"),
            ("Fresh Ginger (Adrak)", "Fresh Harvest", "Daily Staples", "250 g", 60, 48, "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=500&auto=format&fit=crop&q=80", "Potent, fiber-rich ginger root adding aromatic heat to chai and curries.", ["ginger", "adrak", "ginger root"], False, False, False, None),
            ("Fresh Garlic (Lahsun)", "Fresh Harvest", "Daily Staples", "250 g", 65, 52, "https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?w=500&auto=format&fit=crop&q=80", "Plump aromatic garlic cloves for tadkas, pastes, and gravies.", ["garlic", "lahsun", "lasun"], False, True, False, "Best Price"),
            ("Fresh Green Chillies (Hari Mirch)", "Fresh Harvest", "Daily Staples", "100 g", 15, 12, "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=500&auto=format&fit=crop&q=80", "Spicy, crisp green chillies for fiery tadka and green chutneys.", ["green chilli", "hari mirch", "mirchi", "chilli"], False, False, False, None),
            ("Fresh Red Chillies", "Fresh Harvest", "Daily Staples", "100 g", 25, 20, "https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=500&auto=format&fit=crop&q=80", "Vibrant fresh red chillies packed with rich capsaisin and natural spice.", ["red chilli", "lal mirch", "chilli"], False, False, False, None),
            ("Fresh Coriander Leaves (Dhaniya Patta)", "Fresh Harvest", "Leafy Greens", "100 g Bunch", 15, 10, "https://images.unsplash.com/photo-1589135233689-d56d95368a5c?w=500&auto=format&fit=crop&q=80", "Crisp fragrant fresh coriander leaves for vibrant garnishing.", ["coriander", "dhaniya", "dhaniya patta", "cilantro"], False, True, False, "Great Value"),
            ("Fresh Mint Leaves (Pudina)", "Fresh Harvest", "Leafy Greens", "100 g Bunch", 15, 10, "https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=500&auto=format&fit=crop&q=80", "Refreshing cool mint leaves for refreshing juices, raitas, and chutneys.", ["mint", "pudina", "mint leaves"], False, False, False, None),
            ("Fresh Yellow Lemons (Nimbu)", "Fresh Harvest", "Daily Staples", "4 pcs (approx 200g)", 25, 20, "https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=500&auto=format&fit=crop&q=80", "Juicy thin-skinned lemons loaded with fresh Vitamin C.", ["lemon", "nimbu", "citrus"], False, False, False, None),
            ("Orange Carrots (Gajar)", "Fresh Harvest", "Daily Staples", "500 g", 30, 24, "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=500&auto=format&fit=crop&q=80", "Crunchy and sweet farm carrots for salads, stir-fries, and halwa.", ["carrot", "gajar", "carrots"], False, False, False, None),
            ("Fresh Cucumber (Kheera)", "Fresh Harvest", "Daily Staples", "500 g", 25, 19, "https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=500&auto=format&fit=crop&q=80", "Crispy refreshing salad cucumber for cooling daily hydration.", ["cucumber", "kheera", "salad"], False, False, False, None),
            ("Fresh Green Cabbage (Patta Gobhi)", "Fresh Harvest", "Daily Staples", "1 pc (approx 600g)", 30, 22, "https://images.unsplash.com/photo-1551893478-d726eaf0442c?w=500&auto=format&fit=crop&q=80", "Crisp green cabbage heads for stir-fries, momos, and poriyal.", ["cabbage", "patta gobhi", "gobhi"], False, False, False, None),
            ("Fresh Cauliflower (Phool Gobhi)", "Fresh Harvest", "Daily Staples", "1 pc (approx 700g)", 40, 30, "https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?w=500&auto=format&fit=crop&q=80", "Tender white florets packed tightly for aloo gobhi and curries.", ["cauliflower", "phool gobhi", "gobhi"], False, False, False, None),
            ("Fresh Purple Brinjal (Baingan)", "Fresh Harvest", "Daily Staples", "500 g", 30, 24, "https://images.unsplash.com/photo-1528825871115-3581a5387919?w=500&auto=format&fit=crop&q=80", "Glossy purple brinjal ideal for baingan bharta and sambar.", ["brinjal", "baingan", "eggplant"], False, False, False, None),
            ("Tender Lady Finger (Bhindi)", "Fresh Harvest", "Daily Staples", "500 g", 38, 29, "https://images.unsplash.com/photo-1425543103986-22abb7d7e8d2?w=500&auto=format&fit=crop&q=80", "Crisp tender green okra pods that cook crisp without stickiness.", ["lady finger", "bhindi", "okra"], False, True, False, "Best Price"),
            ("Fresh Green Peas (Matar)", "Fresh Harvest", "Daily Staples", "500 g", 45, 35, "https://images.unsplash.com/photo-1587735243615-c03f25aaff15?w=500&auto=format&fit=crop&q=80", "Sweet tender green pea pods full of morning crunch.", ["peas", "matar", "green peas"], False, False, True, "Special Offer"),
            ("Fresh Spinach (Palak)", "Fresh Harvest", "Leafy Greens", "250 g Bunch", 20, 14, "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500&auto=format&fit=crop&q=80", "Tender baby spinach leaves loaded with dietary iron and vitamins.", ["spinach", "palak", "greens"], False, False, False, None),
            ("Fresh Fenugreek (Methi)", "Fresh Harvest", "Leafy Greens", "250 g Bunch", 20, 15, "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=500&auto=format&fit=crop&q=80", "Aromatic methi leaves for comforting parathas and daily sabzi.", ["methi", "fenugreek", "greens"], False, False, False, None),
            ("Fresh Yellow Pumpkin (Kaddu)", "Fresh Harvest", "Gourds & Cucumbers", "500 g Cut", 25, 18, "https://images.unsplash.com/photo-1570586437503-baaeac26e5da?w=500&auto=format&fit=crop&q=80", "Sweet golden pumpkin rich in beta-carotene and dietary fiber.", ["pumpkin", "kaddu", "sitaphal"], False, False, False, None),
            ("Fresh Bottle Gourd (Lauki)", "Fresh Harvest", "Gourds & Cucumbers", "1 pc (approx 700g)", 30, 22, "https://images.unsplash.com/photo-1590165482129-1b8b27698780?w=500&auto=format&fit=crop&q=80", "Tender light bottle gourd for weight-loss juices and light dals.", ["bottle gourd", "lauki", "doodhi", "ghiya"], False, False, False, None),
            ("Fresh Bitter Gourd (Karela)", "Fresh Harvest", "Gourds & Cucumbers", "500 g", 35, 26, "https://images.unsplash.com/photo-1590165482129-1b8b27698780?w=500&auto=format&fit=crop&q=80", "Firm bitter gourds celebrated for health benefits and crispy fries.", ["bitter gourd", "karela"], False, False, False, None),
            ("Fresh Ridge Gourd (Turai)", "Fresh Harvest", "Gourds & Cucumbers", "500 g", 35, 26, "https://images.unsplash.com/photo-1590165482129-1b8b27698780?w=500&auto=format&fit=crop&q=80", "Mild, soft-fleshed ridge gourd delicious in comforting curries.", ["ridge gourd", "turai", "tori"], False, False, False, None),
            ("Fresh White Radish (Mooli)", "Fresh Harvest", "Daily Staples", "500 g", 25, 18, "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=500&auto=format&fit=crop&q=80", "Zesty white mooli with tender leaves for salads and parathas.", ["radish", "mooli", "muli"], False, False, False, None),
            ("Fresh Beetroot (Chukandar)", "Fresh Harvest", "Daily Staples", "500 g", 30, 22, "https://images.unsplash.com/photo-1528825871115-3581a5387919?w=500&auto=format&fit=crop&q=80", "Deep crimson sweet beetroots packed with vitality and nutrients.", ["beetroot", "chukandar", "beet"], False, False, False, None),
            ("Green Capsicum (Shimla Mirch)", "Fresh Harvest", "Daily Staples", "500 g", 48, 36, "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=500&auto=format&fit=crop&q=80", "Juicy crunchy bell peppers for stir-fries, pizza, and curries.", ["capsicum", "shimla mirch", "bell pepper"], False, False, False, "Great Value"),
            ("Fresh French Beans", "Fresh Harvest", "Daily Staples", "500 g", 48, 36, "https://images.unsplash.com/photo-1551893478-d726eaf0442c?w=500&auto=format&fit=crop&q=80", "Tender stringless french beans picked fresh for optimal crunch.", ["green beans", "french beans", "beans"], False, False, False, None),
            ("Sweet Corn Cobs (Pack of 2)", "Fresh Harvest", "Daily Staples", "Pack of 2", 35, 26, "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=500&auto=format&fit=crop&q=80", "Plump sweet golden American corn cobs ready for boiling or grilling.", ["sweet corn", "corn", "bhutta", "makka"], False, False, False, None),
            ("Fresh Button Mushrooms", "Fresh Harvest", "Exotic & Specialty", "200 g Pack", 55, 44, "https://images.unsplash.com/photo-1504472478235-9bc48ba4d60f?w=500&auto=format&fit=crop&q=80", "Pure white hygienic button mushrooms for curries and pizzas.", ["mushroom", "button mushroom", "khumb"], False, False, True, "Today's Deal"),
        ]
    },

    # 2. FRUITS
    {
        "category": "Fruits",
        "sub": "Fresh Fruits",
        "items": [
            ("Kashmiri Royal Delicious Apples", "Fresh Orchard", "Fresh Fruits", "1 kg (approx 5-6 pcs)", 210, 168, "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=500&auto=format&fit=crop&q=80", "Sweet, crisp red Kashmiri apples rich in dietary fiber and vitamins.", ["apple", "seb", "kashmiri apple", "apples"], True, True, False, "Best Price"),
            ("Robusta Fresh Yellow Bananas", "Fresh Orchard", "Fresh Fruits", "1 kg (approx 6-7 pcs)", 65, 52, "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=500&auto=format&fit=crop&q=80", "Naturally ripened yellow bananas rich in instant potassium energy.", ["banana", "kela", "bananas"], True, True, True, "Great Value"),
            ("Nagpur Fresh Sweet Oranges", "Fresh Orchard", "Fresh Fruits", "1 kg", 105, 82, "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?w=500&auto=format&fit=crop&q=80", "Famous sweet-tangy Nagpur oranges packed with natural Vitamin C.", ["orange", "santra", "citrus"], True, False, False, None),
            ("Ratnagiri Alphonso Mango", "Fresh Orchard", "Fresh Fruits", "1 kg (approx 3 pcs)", 320, 260, "https://images.unsplash.com/photo-1553279768-865429fa0078?w=500&auto=format&fit=crop&q=80", "Rich, fragrant king of mangoes with golden sweet pulp.", ["mango", "aam", "alphonso", "hapus"], True, True, False, "Special Offer"),
            ("Fresh Seedless Green Grapes", "Fresh Orchard", "Fresh Fruits", "500 g", 65, 49, "https://images.unsplash.com/photo-1596363505729-4190a9506133?w=500&auto=format&fit=crop&q=80", "Crisp and juicy sweet green seedless grapes.", ["grapes", "angoor", "green grapes"], False, False, True, "Today's Deal"),
            ("Fresh Allahabad Guava (Amrood)", "Fresh Orchard", "Fresh Fruits", "1 kg", 75, 58, "https://images.unsplash.com/photo-1536511135896-1c88dbda097e?w=500&auto=format&fit=crop&q=80", "Sweet fragrant white guavas loaded with exceptional fiber and Vitamin C.", ["guava", "amrood", "peru"], False, False, False, None),
            ("Sweet Red Papaya", "Fresh Orchard", "Fresh Fruits", "1 pc (approx 1.2kg)", 65, 48, "https://images.unsplash.com/photo-1617112848923-cc2234396a8d?w=500&auto=format&fit=crop&q=80", "Deep orange sweet honey papaya aiding digestion and wellness.", ["papaya", "papita"], False, False, False, None),
            ("Striped Sweet Watermelon (Tarbooz)", "Fresh Orchard", "Fresh Fruits", "1 pc (approx 2.5kg)", 95, 75, "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500&auto=format&fit=crop&q=80", "Juicy, vibrant red-fleshed refreshing watermelon.", ["watermelon", "tarbooz", "melon"], False, True, False, "Great Value"),
            ("Golden Sweet Muskmelon (Kharbooja)", "Fresh Orchard", "Fresh Fruits", "1 pc (approx 900g)", 55, 42, "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=500&auto=format&fit=crop&q=80", "Fragrant muskmelon with succulent, honey-sweet orange flesh.", ["muskmelon", "kharbooja", "cantaloupe"], False, False, False, None),
            ("Ruby Red Pomegranate (Anaar)", "Fresh Orchard", "Fresh Fruits", "1 kg", 230, 185, "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=500&auto=format&fit=crop&q=80", "Plump ruby-red arils packed with powerful heart antioxidants.", ["pomegranate", "anaar", "anar"], False, True, False, "Best Price"),
            ("Golden Pineapple (Ananas)", "Fresh Orchard", "Fresh Fruits", "1 pc (approx 1kg)", 85, 68, "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=500&auto=format&fit=crop&q=80", "Juicy tropical golden pineapple with sweet and tangy pulp.", ["pineapple", "ananas"], False, False, False, None),
            ("Tender Coconut with Water", "Fresh Orchard", "Fresh Fruits", "1 pc", 60, 49, "https://images.unsplash.com/photo-1544378730-8b5104b18790?w=500&auto=format&fit=crop&q=80", "Natural electrolyte coconut water with soft tender malai inside.", ["coconut", "nariyal", "tender coconut"], False, True, True, "Today's Deal"),
            ("Fresh Green Kiwi Fruit", "Fresh Orchard", "Fresh Fruits", "Pack of 3", 110, 89, "https://images.unsplash.com/photo-1585059895524-72359e06133a?w=500&auto=format&fit=crop&q=80", "Zesty green kiwi loaded with actinidin digestive enzymes.", ["kiwi", "kiwifruit"], False, False, False, None),
            ("Juicy Green Pears (Nashpati)", "Fresh Orchard", "Fresh Fruits", "1 kg", 160, 128, "https://images.unsplash.com/photo-1514756331096-242fdeb70d4a?w=500&auto=format&fit=crop&q=80", "Crunchy and sweet green pears full of dietary fiber.", ["pear", "nashpati"], False, False, False, None),
            ("Fresh Strawberries Box", "Fresh Orchard", "Fresh Fruits", "200 g Box", 90, 69, "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=500&auto=format&fit=crop&q=80", "Fragrant crimson strawberries handpicked from Mahabaleshwar.", ["strawberry", "strawberries", "berries"], False, False, True, "Special Offer"),
            ("Sweet Lime (Mosambi)", "Fresh Orchard", "Fresh Fruits", "1 kg", 85, 68, "https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=500&auto=format&fit=crop&q=80", "Sweet and gentle citrus mosambi for healthy freshly squeezed juices.", ["sweet lime", "mosambi", "citrus"], False, False, False, None),
            ("Fresh Chikoo (Sapota)", "Fresh Orchard", "Fresh Fruits", "1 kg", 85, 68, "https://images.unsplash.com/photo-1553279768-865429fa0078?w=500&auto=format&fit=crop&q=80", "Caramel-sweet soft chikoo loaded with natural wholesome energy.", ["chikoo", "sapota", "chiku"], False, False, False, None),
            ("Fresh Shahi Lychee", "Fresh Orchard", "Fresh Fruits", "500 g", 140, 110, "https://images.unsplash.com/photo-1596363505729-4190a9506133?w=500&auto=format&fit=crop&q=80", "Juicy translucent sweet lychees bursting with tropical floral aroma.", ["lychee", "litchi", "lichi"], False, False, False, None),
        ]
    },

    # 3. SPICES & MASALA
    {
        "category": "Spices & Masala",
        "sub": "Powdered & Whole Spices",
        "items": [
            ("Everest Tikhalal Red Chilli Powder", "Everest", "Powdered Spices", "500 g", 260, 225, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Finely ground hot red chilli powder delivering fiery taste and vibrant color.", ["chilli powder", "lal mirch", "mirch powder", "everest chilli"], True, True, False, "Best Price"),
            ("Catch Turmeric Powder (Haldi)", "Catch", "Powdered Spices", "500 g", 195, 168, "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=500&auto=format&fit=crop&q=80", "High curcumin golden turmeric powder ground from selected Salem roots.", ["haldi", "turmeric", "haldi powder", "catch haldi"], True, True, False, "Great Value"),
            ("MDH Dhania Powder (Coriander)", "MDH", "Powdered Spices", "500 g", 185, 158, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Cold-ground coriander powder preserving essential citrusy essential oils.", ["coriander powder", "dhania", "dhaniya powder", "mdh"], False, False, False, None),
            ("Everest Jeera Powder (Cumin)", "Everest", "Powdered Spices", "100 g", 80, 68, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Aromatic roasted cumin powder for raitas, gravies, and snacks.", ["cumin powder", "jeera powder", "jeera"], False, False, False, None),
            ("MDH Garam Masala", "MDH", "Blended Masalas", "100 g", 98, 85, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Classic blend of 15 authentic whole spices ground to royal perfection.", ["garam masala", "mdh garam masala", "masala"], True, True, True, "Today's Deal"),
            ("Catch Chaat Masala Spinkler", "Catch", "Blended Masalas", "100 g", 68, 58, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Tangy and savory seasoning blend for salads, fruits, and street snacks.", ["chaat masala", "catch chaat masala", "sprinkler"], False, True, False, None),
            ("Everest Kitchen King Masala", "Everest", "Blended Masalas", "100 g", 88, 76, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Versatile aromatic spice blend that elevates any vegetable or paneer curry.", ["kitchen king", "kitchen king masala", "everest"], False, False, False, None),
            ("Everest Pav Bhaji Masala", "Everest", "Blended Masalas", "100 g", 85, 72, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Signature spice blend for authentic Mumbai-style buttery pav bhaji.", ["pav bhaji masala", "pav bhaji", "everest"], False, False, False, None),
            ("MDH Chana Masala (Chole Masala)", "MDH", "Blended Masalas", "100 g", 88, 75, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Pungent, tangy masala blend creating rich Punjabi chole and bhature curry.", ["chole masala", "chana masala", "mdh chana"], False, False, False, None),
            ("Everest Chicken Masala", "Everest", "Blended Masalas", "100 g", 95, 82, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Aromatic rich spice mix creating mouth-watering chicken gravies.", ["chicken masala", "meat masala", "everest"], False, False, False, None),
            ("Kohinoor Hyderabadi Biryani Masala", "Kohinoor", "Blended Masalas", "100 g", 110, 92, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Royal Mughlai blend of saffron, mace, and star anise for aromatic dum biryani.", ["biryani masala", "hyderabadi biryani masala", "biryani"], False, True, False, "Special Offer"),
            ("Catch Black Pepper Powder (Kali Mirch)", "Catch", "Powdered Spices", "100 g", 145, 125, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Bold Malabar black pepper powder with intense spicy warmth.", ["black pepper", "kali mirch", "pepper"], False, False, False, None),
            ("Tata Sampann Whole Cumin Seeds (Jeera)", "Tata Sampann", "Whole Spices", "200 g", 160, 135, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Selected whole unadulterated jeera with high essential oil content.", ["cumin", "jeera", "whole cumin", "zeera"], True, True, False, "Best Price"),
            ("Catch Whole Cloves (Laung)", "Catch", "Whole Spices", "50 g", 110, 92, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Plump aromatic whole cloves rich in eugenol for immunity and rich flavor.", ["cloves", "laung", "long", "spices"], False, False, False, None),
            ("Tata Sampann Green Cardamom (Elaichi)", "Tata Sampann", "Whole Spices", "50 g", 240, 198, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Plump 8mm green cardamom pods bursting with sweet royal fragrance for sweets and chai.", ["cardamom", "elaichi", "green cardamom", "elachi"], True, True, True, "Today's Deal"),
            ("Catch Dalchini / Cinnamon Sticks", "Catch", "Whole Spices", "100 g", 125, 105, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Fragrant sweet cinnamon quills for curries, bakes, and herbal tea infusions.", ["cinnamon", "dalchini", "whole cinnamon"], False, False, False, None),
            ("Catch Bay Leaf (Tej Patta)", "Catch", "Whole Spices", "50 g", 45, 36, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Whole aromatic dried bay leaves for seasoning fragrant rice and slow curries.", ["bay leaf", "tej patta", "tejpatta"], False, False, False, None),
            ("Tata Sampann Black Mustard Seeds (Rai)", "Tata Sampann", "Whole Spices", "200 g", 65, 52, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Pungent clean black mustard seeds essential for South Indian tadka.", ["mustard seeds", "rai", "sarson", "black mustard"], False, False, False, None),
            ("Catch Saunf (Fennel Seeds)", "Catch", "Whole Spices", "100 g", 60, 49, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Sweet aromatic fennel seeds for digestive mouth freshening and curries.", ["fennel", "saunf", "variyali", "fennel seeds"], False, False, False, None),
            ("Catch Methi Dana (Fenugreek Seeds)", "Catch", "Whole Spices", "100 g", 45, 36, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Golden fenugreek seeds aiding digestion and adding depth to pickles.", ["fenugreek", "methi dana", "methi seeds"], False, False, False, None),
            ("Catch Carom Seeds (Ajwain)", "Catch", "Whole Spices", "100 g", 55, 45, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Pungent thymol-rich ajwain seeds for crispy puris, samosas, and digestion.", ["ajwain", "carom seeds", "ajowan"], False, False, False, None),
            ("Catch Compounded Asafoetida (Hing)", "Catch", "Powdered Spices", "50 g", 95, 82, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Strong authentic hing delivering traditional aromatic punch to dal tadka.", ["hing", "asafoetida", "compounded hing"], False, True, False, "Great Value"),
            ("Catch Kala Namak (Black Salt)", "Catch", "Salts", "100 g", 35, 28, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Traditional mineral-rich Himalayan black salt for chaats, raitas, and juices.", ["black salt", "kala namak", "salt"], False, False, False, None),
            ("Tata Rock Salt (Sendha Namak)", "Tata", "Salts", "1 kg", 95, 82, "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", "Pure natural rock salt ideal for daily wellness and fasting (vrat).", ["rock salt", "sendha namak", "himalayan pink salt"], False, False, False, None),
            ("Tata Salt Vacuum Evaporated Iodised", "Tata", "Salts", "1 kg", 28, 26, "https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?w=500&auto=format&fit=crop&q=80", "India's trusted vacuum evaporated iodised salt ensuring mental development.", ["regular salt", "salt", "tata salt", "namak"], True, True, False, "Best Price")
        ]
    },

    # 4. RICE & GRAINS
    {
        "category": "Rice & Grains",
        "sub": "Rice & Healthy Grains",
        "items": [
            ("India Gate Feast Rozzana Basmati Rice", "India Gate", "Basmati Rice", "5 kg", 650, 599, "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80", "Aged long-grain basmati rice with exquisite aroma for family meals.", ["basmati rice", "india gate", "rice", "biryani rice"], True, True, False, "Best Price"),
            ("Daawat Rozana Gold Basmati Rice", "Daawat", "Basmati Rice", "5 kg", 590, 525, "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80", "Medium-to-long grain basmati rice perfect for daily dal chawal and pulao.", ["basmati rice", "daawat", "rice"], False, True, False, "Great Value"),
            ("Fortune Everyday Basmati Rice", "Fortune", "Basmati Rice", "1 kg", 115, 95, "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80", "Hygienically sorted aromatic basmati rice for everyday nutrition.", ["basmati rice", "fortune", "rice"], False, False, False, None),
            ("Kohinoor Super Silver Basmati Rice", "Kohinoor", "Basmati Rice", "5 kg", 720, 640, "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80", "Fluffy, fragrant extra long grains aged over 2 years for banquets and celebrations.", ["basmati rice", "kohinoor", "rice"], False, False, True, "Today's Deal"),
            ("Sona Masoori Raw Rice", "Fresh Harvest", "Regular Rice", "5 kg", 390, 335, "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80", "Lightweight, aromatic South Indian daily staple raw rice.", ["regular rice", "sona masoori", "rice", "chawal"], True, True, False, "Best Price"),
            ("Golden Sella Parboiled Basmati Rice", "India Gate", "Sella Rice", "5 kg", 680, 599, "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80", "Hardened parboiled long grains that never break or get sticky during biryani preparation.", ["sella rice", "parboiled rice", "basmati sella"], False, False, False, None),
            ("Daawat Quick Cooking Brown Rice", "Daawat", "Brown Rice", "1 kg", 175, 145, "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80", "Wholesome fiber-rich unpolished brown rice with zero cholesterol.", ["brown rice", "daawat brown rice", "healthy rice"], False, False, False, None),
            ("Tata Sampann Thick Poha (Flattened Rice)", "Tata Sampann", "Breakfast Grains", "1 kg", 95, 78, "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80", "High fiber flattened rice flakes for quick healthy breakfast batata poha.", ["poha", "flattened rice", "avalakki", "chivda"], True, True, False, "Great Value"),
            ("Fresh Crisp Puffed Rice (Murmura)", "Fresh Harvest", "Snack Grains", "500 g", 50, 38, "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80", "Crispy light puffed rice for authentic bhel puri, murmura laddoos, and light diet snacking.", ["murmura", "puffed rice", "kurmura", "mamra"], True, False, False, None),
            ("Organic Broken Wheat Dalia", "Natureland", "Healthy Grains", "500 g", 65, 52, "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80", "Cracked whole wheat grain providing prolonged energy and wholesome fiber.", ["dalia", "broken wheat", "fada", "porridge"], False, False, False, None),
            ("Quaker Rolled Oats", "Quaker", "Healthy Grains", "1 kg", 225, 185, "https://images.unsplash.com/photo-1521483451569-e33803c0330c?w=500&auto=format&fit=crop&q=80", "100% wholegrain rolled oats helping reduce cholesterol and manage weight.", ["oats", "quaker oats", "breakfast oats"], False, True, False, "Best Price"),
            ("Nature's Basket Organic White Quinoa", "Nature's Basket", "Healthy Grains", "500 g", 280, 225, "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80", "Gluten-free complete plant protein grain containing all 9 essential amino acids.", ["quinoa", "white quinoa", "superfood"], False, False, False, None),
            ("Patanjali Whole Grain Barley (Jau)", "Patanjali", "Healthy Grains", "500 g", 55, 45, "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80", "High fiber barley grains great for refreshing barley water and soup porridge.", ["barley", "jau", "grains"], False, False, False, None)
        ]
    },

    # 5. ATTA & FLOUR
    {
        "category": "Atta & Flour",
        "sub": "Flours & Grains",
        "items": [
            ("Aashirvaad Shudh Chakki Wheat Atta", "Aashirvaad", "Whole Wheat", "5 kg", 285, 255, "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80", "100% pure whole wheat grain flour traditional stone ground for soft rotis.", ["wheat atta", "atta", "aashirvaad atta", "chakki atta"], True, True, False, "Best Price"),
            ("Aashirvaad Multigrain Atta", "Aashirvaad", "Specialty Atta", "5 kg", 345, 299, "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80", "Nutritious blend of 6 grains including soya, chana, oat, maize, and psyllium husk.", ["multigrain atta", "multigrain", "aashirvaad multigrain"], False, True, False, "Great Value"),
            ("Fortune Chakki Fresh Atta", "Fortune", "Whole Wheat", "10 kg", 530, 465, "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80", "Nutritious chakki fresh atta made with high quality wheat grains.", ["wheat atta", "fortune atta", "atta 10kg"], False, False, True, "Today's Deal"),
            ("Pillsbury Traditional Chakki Atta", "Pillsbury", "Whole Wheat", "5 kg", 280, 248, "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80", "Provides soft rotis that remain tender for up to 6 hours.", ["atta", "pillsbury", "wheat flour"], False, False, False, None),
            ("Rajdhani Refined Wheat Flour (Maida)", "Rajdhani", "Refined Flour", "1 kg", 55, 45, "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80", "Silky smooth refined flour for baking cakes, naan, puris, and samosas.", ["maida", "refined flour", "all purpose flour"], False, False, False, None),
            ("Fortune Pure Besan (Gram Flour)", "Fortune", "Gram Flour", "1 kg", 125, 99, "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80", "100% chana dal besan with fine texture for crispy pakoras, dhokla, and sweets.", ["besan", "gram flour", "chana flour"], True, True, False, "Best Price"),
            ("Rajdhani Granular Semolina (Suji / Rawa)", "Rajdhani", "Semolina", "500 g", 45, 36, "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80", "Crisp roasted suji for halwa, upma, rawa dosas, and crispy snacks.", ["suji", "sooji", "rava", "semolina"], False, False, False, None),
            ("24 Mantra Organic Rice Flour", "24 Mantra", "Rice Flour", "500 g", 55, 44, "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80", "Finely milled white rice flour for crispy murukku, dosas, and modaks.", ["rice flour", "chawal ka atta", "arisi maavu"], False, False, False, None),
            ("Brown & Polson Fine Corn Flour", "Brown & Polson", "Corn Flour", "500 g", 75, 62, "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80", "Essential kitchen starch for thickening soups, gravies, and making crispy snacks.", ["corn flour", "cornflour", "corn starch"], False, False, False, None),
            ("Patanjali Pure Ragi Flour (Finger Millet)", "Patanjali", "Millet Flour", "500 g", 60, 48, "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80", "Calcium-dense finger millet ragi flour for wholesome rotis and porridge.", ["ragi flour", "ragi", "finger millet", "nachni"], False, False, False, None),
            ("Organic Pearl Millet Bajra Flour", "Natureland", "Millet Flour", "500 g", 55, 44, "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80", "Nutritious warming winter millet flour for traditional bajra rotis.", ["bajra flour", "bajra", "pearl millet"], False, False, False, None),
            ("Pure Sorghum Jowar Flour", "Natureland", "Millet Flour", "500 g", 60, 48, "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80", "Gluten-free cooling sorghum jowar flour rich in potassium and fiber.", ["jowar flour", "jowar", "sorghum"], False, False, False, None)
        ]
    }
]

print("Built initial structures...")
